var jsondata = `
  {
  "RECORDS": [
    {
      "nom": 0,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：それは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "不听",
      "B": "不知道",
      "C": "做不到",
      "D": "不一样",
      "E": "我不知道这个词",
      "target": "違う",
      "correct": "D"
  },
    {
      "nom": 1,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは一種の<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>だ。",
      "A": "无法用语言表达的感情",
      "B": "自我牺牲的爱",
      "C": "把两个对立的事物合二为一地看待的方法",
      "D": "通过类比成相似事物来进行的理解或说明",
      "E": "我不知道这个词",
      "target": "アナロジー",
      "correct": "D"
  },
  {
      "nom": 2,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：ここには三つの<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>があります。",
      "A": "群体",
      "B": "案例",
      "C": "类型",
      "D": "等级",
      "E": "我不知道这个词",
      "target": "団体",
      "correct": "A"
  },
  {
      "nom": 3,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が好きだ。",
      "A": "用面粉、鸡蛋等调制烘培出来的食物",
      "B": "德国的快车道",
      "C": "1950年代在全世界流行的音乐",
      "D": "无色而味重的饮料",
      "E": "我不知道这个词",
      "target": "パンケーキ",
      "correct": "A"
  },
  {
      "nom": 4,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：ついに<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が来た。",
      "A": "晚点了的交通工具",
      "B": "出场的场面",
      "C": "非常艰难的状况",
      "D": "受到好评的电影",
      "E": "我不知道这个词",
      "target": "出番",
      "correct": "B"
  },
  {
      "nom": 5,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>は何を示すか。",
      "A": "基于某种标准用来表示变动情况的数字",
      "B": "参与者的人数",
      "C": "对应关系的种类数",
      "D": "表示指令复杂程度的数字",
      "E": "我不知道这个词",
      "target": "指数",
      "correct": "A"
  },
  {
      "nom": 6,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この小説の<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>は何ですか。",
      "A": "深层思想",
      "B": "好笑的地方",
      "C": "故事原型",
      "D": "用于练笔的作品",
      "E": "我不知道这个词",
      "target": "元ねた",
      "correct": "C"
  },
  {
      "nom": 7,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人に<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>のはやめよう。",
      "A": "代替某人工作",
      "B": "巴结、讨好某人",
      "C": "在某人面前表现出很擅长的样子",
      "D": "将其他人介绍给某人",
      "E": "我不知道这个词",
      "target": "おもねる",
      "correct": "B"
  },
  {
      "nom": 8,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspをついたまま</u>動かない。",
      "A": "张开腿坐着",
      "B": "头靠着墙",
      "C": "单脚站着",
      "D": "支起手肘，用手掌托着脸颊",
      "E": "我不知道这个词",
      "target": "頬杖",
      "correct": "D"
  },
  {
      "nom": 9,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あれとこれを<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspしよう</u>。",
      "A": "合并成一个吧",
      "B": "一起使用吧",
      "C": "调换一下吧",
      "D": "在线上进行排列吧",
      "E": "我不知道这个词",
      "target": "併用",
      "correct": "B"
  },
  {
      "nom": 10,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の人だ。",
      "A": "从零开始学习，一点点获得实力的人",
      "B": "一出生就拥有很高地位的人",
      "C": "酒喝多了的人",
      "D": "能理解别人心情的人",
      "E": "我不知道这个词",
      "target": "たたき上げ",
      "correct": "A"
  },
  {
      "nom": 11,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：来月、<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspを行う</u>ことになった。",
      "A": "换一个迄今为止最好的工作",
      "B": "国家或企业从外界借钱",
      "C": "针对某事件打官司",
      "D": "做预防疾病的措施",
      "E": "我不知道这个词",
      "target": "起債",
      "correct": "B"
  },
  {
      "nom": 12,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この番組には<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>がない。",
      "A": "关于情景、故事脉络等的说明",
      "B": "承担制作费用的公司",
      "C": "中途插播的广告",
      "D": "作为背景播放的音乐",
      "E": "我不知道这个词",
      "target": "ＢＧＭ",
      "correct": "D"
  },
  {
      "nom": 13,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspいた</u>。",
      "A": "非常着急地赶了过去",
      "B": "重启攻势发起了攻击",
      "C": "充满了强烈的想要努力的心情",
      "D": "因感到恐惧而身体无法动弹了",
      "E": "我不知道这个词",
      "target": "気負い立つ",
      "correct": "C"
  },
  {
      "nom": 14,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：それは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の仕事だ。",
      "A": "完成了大学学业的人",
      "B": "持有职业资格证书的人",
      "C": "地位不高的士兵",
      "D": "上了年纪的士兵",
      "E": "我不知道这个词",
      "target": "士卒",
      "correct": "C"
  },
  {
      "nom": 15,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>について勉強した。",
      "A": "管理武士的组织",
      "B": "为了城镇工作的人",
      "C": "在船上唱的歌",
      "D": "为了食用而种植的蔬菜",
      "E": "我不知道这个词",
      "target": "侍所",
      "correct": "A"
  },
  {
      "nom": 16,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：屋上、屋<u>を&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "在……上加上颜色、图案等",
      "B": "把……通过语言讲出来",
      "C": "把……沿着墙壁延展开",
      "D": "把……接着往上做",
      "E": "我不知道这个词",
      "target": "架する",
      "correct": "D"
  },
  {
      "nom": 17,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspような声</u>で話した。",
      "A": "如唱歌一般的声音",
      "B": "快要听不见的声音",
      "C": "高音",
      "D": "远处都可以听到的声音",
      "E": "我不知道这个词",
      "target": "消え入る",
      "correct": "B"
  },
  {
      "nom": 18,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を選ぶ。",
      "A": "已婚女士在婚礼上的穿着",
      "B": "在外国（比如欧美各国）出版的书",
      "C": "和服衬衣上围绕在脖子周围的部分",
      "D": "内含钻石等成分的石头",
      "E": "我不知道这个词",
      "target": "半襟",
      "correct": "C"
  },
  {
      "nom": 19,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：貼ってある紙を<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "争夺",
      "B": "一口气扯下",
      "C": "偷拿出来据为己有",
      "D": "手拿着向上举高",
      "E": "我不知道这个词",
      "target": "引きはがす",
      "correct": "B"
  },
  {
      "nom": 20,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：工事の終わりが<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "推迟后发生变化",
      "B": "离得很远",
      "C": "提前",
      "D": "被搁置",
      "E": "我不知道这个词",
      "target": "ずれこむ",
      "correct": "A"
  },
  {
      "nom": 21,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：多くの<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>でにぎわっている。",
      "A": "来观赏游玩的人",
      "B": "与音乐相关的人",
      "C": "武士中年纪较轻的人",
      "D": "40多岁到50多岁的女人",
      "E": "我不知道这个词",
      "target": "遊客",
      "correct": "A"
  },
  {
      "nom": 22,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>セールに行く。",
      "A": "在各种地方广泛使用",
      "B": "清理剩余的物品",
      "C": "到处都有",
      "D": "通知大家",
      "E": "我不知道这个词",
      "target": "クリアランス",
      "correct": "B"
  },
  {
      "nom": 23,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：ここには年齢が<u>30&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の人が多い。",
      "A": "30或者大于30",
      "B": "正好30",
      "C": "大于30",
      "D": "小于30",
      "E": "我不知道这个词",
      "target": "未満",
      "correct": "D"
  },
  {
      "nom": 24,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspで</u>提供された。",
      "A": "明明不需要但强行",
      "B": "在最好的时机",
      "C": "通过政府官方地",
      "D": "不需要交钱，免费的",
      "E": "我不知道这个词",
      "target": "無償",
      "correct": "D"
  },
  {
      "nom": 25,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：多くの人が<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspした</u>。",
      "A": "觉得悲伤遗憾",
      "B": "一天也不休息地工作",
      "C": "判断了是好还是坏",
      "D": "没给钱但给了物品作为替代",
      "E": "我不知道这个词",
      "target": "品評",
      "correct": "C"
  },
  {
      "nom": 26,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：どんな<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が表されていますか。",
      "A": "其他的思考、想法",
      "B": "作画者的心情",
      "C": "插在中间的话",
      "D": "对逝者的思念",
      "E": "我不知道这个词",
      "target": "寓意",
      "correct": "A"
  },
  {
      "nom": 27,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：鳥のようなものが<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "以很陡的角度上升",
      "B": "滑下来",
      "C": "从空中轻柔地落下",
      "D": "从高处向上飞",
      "E": "我不知道这个词",
      "target": "舞い降りる",
      "correct": "C"
  },
  {
      "nom": 28,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を見るのが好きだ。",
      "A": "演奏音乐的团队",
      "B": "规模宏大的作品",
      "C": "认真的脸",
      "D": "逗笑观众的戏剧",
      "E": "我不知道这个词",
      "target": "喜劇",
      "correct": "D"
  },
  {
      "nom": 29,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この会社は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspしている</u>。",
      "A": "失去了活力",
      "B": "处于混乱的状态",
      "C": "气氛活跃",
      "D": "变得富有",
      "E": "我不知道这个词",
      "target": "ゴタゴタ",
      "correct": "B"
  },
  {
      "nom": 30,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspした</u>ところである。",
      "A": "开始营业",
      "B": "写成文章",
      "C": "选取出来",
      "D": "开始在丈夫家生活",
      "E": "我不知道这个词",
      "target": "店開き",
      "correct": "A"
  },
  {
      "nom": 31,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を買う。",
      "A": "浇在食物上面的白色的东西",
      "B": "在节日庆典活动中用作装饰的物品",
      "C": "灌水后用来给头部降温的东西",
      "D": "喝酒时使用的东西",
      "E": "我不知道这个词",
      "target": "練乳",
      "correct": "A"
  },
  {
      "nom": 32,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を失っていない。",
      "A": "像孩子一样的心情",
      "B": "尖锐的批评",
      "C": "收敛的行为",
      "D": "原本主要想表达的意思",
      "E": "我不知道这个词",
      "target": "童心",
      "correct": "A"
  },
  {
      "nom": 33,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：私はあの人に<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>もらった。",
      "A": "看着周围",
      "B": "照顾养育",
      "C": "讲秘密",
      "D": "买礼物",
      "E": "我不知道这个词",
      "target": "養う",
      "correct": "B"
  },
  {
      "nom": 34,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を利用したものだ。",
      "A": "从鱼身上取下来的、有气味的油",
      "B": "庭院里经常种植的、会开白色花朵的树",
      "C": "酿酒后留下来的东西",
      "D": "会在沙拉等料理中使用到的红色圆形蔬菜",
      "E": "我不知道这个词",
      "target": "酒かす",
      "correct": "C"
  },
  {
      "nom": 35,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspをしたら</u>知らせてください。",
      "A": "交了钱的话",
      "B": "做了记录的话",
      "C": "失败、弄错的话",
      "D": "负责人换了的话",
      "E": "我不知道这个词",
      "target": "ミス",
      "correct": "C"
  },
  {
      "nom": 36,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：今は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspの</u>ときだ。",
      "A": "忍耐住等待机会的",
      "B": "加上欠缺内容的",
      "C": "团结成一体的",
      "D": "在某个特定的部分下功夫的",
      "E": "我不知道这个词",
      "target": "雌伏",
      "correct": "A"
  },
  {
      "nom": 37,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を見た。",
      "A": "刚从身体里流出来的红色的东西",
      "B": "做得很相似的东西",
      "C": "看上去泛着白光的东西",
      "D": "事情发生的契机",
      "E": "我不知道这个词",
      "target": "生血",
      "correct": "A"
  },
  {
      "nom": 38,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が大きい。",
      "A": "售出金额和买入金额的差",
      "B": "觉得喜欢的那种心情",
      "C": "牙齿和牙齿之间发出的声音",
      "D": "像石头一样顽固的脑袋",
      "E": "我不知道这个词",
      "target": "利ざや",
      "correct": "A"
  },
  {
      "nom": 39,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：月に１回<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>をする。",
      "A": "去专门的地方祈祷",
      "B": "小孩子去学校",
      "C": "在别的地方写出来展示",
      "D": "为了表示感谢寄送钱、物品等",
      "E": "我不知道这个词",
      "target": "寺詣で",
      "correct": "A"
  },
  {
      "nom": 40,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp文句</u>はよかった。",
      "A": "表示强烈请求的话",
      "B": "表示歉意的话",
      "C": "表示同感的话",
      "D": "表示感谢的话",
      "E": "我不知道这个词",
      "target": "口説き",
      "correct": "A"
  },
  {
      "nom": 41,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>だ。",
      "A": "戴在脖子上的装饰品",
      "B": "做得不易生锈的金属",
      "C": "为了挡住光、声音等在窗前或室内挂的布",
      "D": "不可思议的、神秘的谜团",
      "E": "我不知道这个词",
      "target": "ステンレス",
      "correct": "B"
  },
  {
      "nom": 42,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp絞めに</u>した。",
      "A": "采取旁若无人的态度",
      "B": "将别人的胳膊绕到其背后，并使之无法动弹",
      "C": "当作从未约定过",
      "D": "让别人承担责任",
      "E": "我不知道这个词",
      "target": "羽交い",
      "correct": "B"
  },
  {
      "nom": 43,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "开朗、快乐",
      "B": "美丽、漂亮",
      "C": "细致、正确",
      "D": "了不起、地位高",
      "E": "我不知道这个词",
      "target": "偉い",
      "correct": "D"
  },
  {
      "nom": 44,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspの</u>馬がほしい。",
      "A": "整体呈褐色，部分呈黑色的",
      "B": "名字广为人知的",
      "C": "被大家所称赞的",
      "D": "不惧危险且强大的",
      "E": "我不知道这个词",
      "target": "鹿毛",
      "correct": "A"
  },
  {
      "nom": 45,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp生</u>だった。",
      "A": "江户时代做着类似银行工作的人",
      "B": "搬运沉重行李的人",
      "C": "应当以礼相待的人",
      "D": "学习绘画的人",
      "E": "我不知道这个词",
      "target": "画学",
      "correct": "D"
  },
  {
      "nom": 46,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：その後まもなく<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が起こった。",
      "A": "丢掉不需要的东西",
      "B": "有很多人参与的争斗",
      "C": "改变前进方向",
      "D": "武士（主导的）政治",
      "E": "我不知道这个词",
      "target": "戦役",
      "correct": "B"
  },
  {
      "nom": 47,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：それは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>にあった。",
      "A": "做学问和研究的中心",
      "B": "为人师者应选择的道路",
      "C": "书的开头",
      "D": "脱鞋的地方",
      "E": "我不知道这个词",
      "target": "巻首",
      "correct": "C"
  },
  {
      "nom": 48,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspだ</u>。",
      "A": "不拘小节",
      "B": "看见时心情不悦",
      "C": "没有喝水",
      "D": "讲有趣的事情",
      "E": "我不知道这个词",
      "target": "目障り",
      "correct": "B"
  },
  {
      "nom": 49,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が高くなった。",
      "A": "全世界通用的货币单位",
      "B": "处理图像时的颜色信息单位",
      "C": "用于连接电脑和其他设备的东西",
      "D": "将礼物等包裹起来的东西，如精美的纸张",
      "E": "我不知道这个词",
      "target": "ＳＤＲ",
      "correct": "A"
  },
  {
      "nom": 50,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：いちばんいいものを<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "考虑方法和手段，然后行动",
      "B": "从水中取上来",
      "C": "使……广为人知",
      "D": "大加夸赞",
      "E": "我不知道这个词",
      "target": "講ずる",
      "correct": "A"
  },
  {
      "nom": 51,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：全国に<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp教室</u>がある。",
      "A": "下课之后去的教室",
      "B": "学校外面的教室",
      "C": "用来玩耍的教室",
      "D": "聚集了各种人的教室",
      "E": "我不知道这个词",
      "target": "サテライト",
      "correct": "B"
  },
  {
      "nom": 52,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>をしよう。",
      "A": "给受灾的人提供餐食",
      "B": "不考虑质量地大量制作、生产",
      "C": "把积雪扫开",
      "D": "在交谈的场合中提出意见",
      "E": "我不知道这个词",
      "target": "炊き出し",
      "correct": "A"
  },
  {
      "nom": 53,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspがある</u>。",
      "A": "聪明的头脑",
      "B": "做东西的能力",
      "C": "敢于挑战的心",
      "D": "从容的状态",
      "E": "我不知道这个词",
      "target": "ゆとり",
      "correct": "D"
  },
  {
      "nom": 54,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：相手を<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "踢倒了……",
      "B": "邀请了……成为伙伴",
      "C": "随心所欲地使唤了……",
      "D": "打败了……",
      "E": "我不知道这个词",
      "target": "討ち取る",
      "correct": "D"
  },
  {
      "nom": 55,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼女は彼を<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "重新审视后，觉得还不错",
      "B": "觉得不行了，然后放弃并离开",
      "C": "虽然看到了，但装作没看到",
      "D": "盯着看，但最终看不到了",
      "E": "我不知道这个词",
      "target": "見放す",
      "correct": "B"
  },
  {
      "nom": 56,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：問題は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspすぎる</u>ことだ。",
      "A": "太简单",
      "B": "太遗憾",
      "C": "太干净",
      "D": "太不坦率",
      "E": "我不知道这个词",
      "target": "軽易",
      "correct": "A"
  },
  {
      "nom": 57,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この果物は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspだ</u>。",
      "A": "和普通的相比成熟较晚",
      "B": "逐渐变大",
      "C": "呈淡黄色",
      "D": "容易裂开",
      "E": "我不知道这个词",
      "target": "晩生",
      "correct": "A"
  },
  {
      "nom": 58,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：ここは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>がよい。",
      "A": "做生意的条件",
      "B": "设备",
      "C": "太阳光的状态",
      "D": "氛围",
      "E": "我不知道这个词",
      "target": "ムード",
      "correct": "D"
  },
  {
      "nom": 59,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：私の<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>はどこへ行ったのだろう。",
      "A": "经验和获得的能力",
      "B": "强大的勇气",
      "C": "秘密的地方",
      "D": "年轻有活力的时代",
      "E": "我不知道这个词",
      "target": "青春",
      "correct": "D"
  },
  {
      "nom": 60,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼は周囲<u>を&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspした</u>。",
      "A": "调查……的敌人的情况",
      "B": " 进入……的人群中隐藏起来",
      "C": "说服……推进事业",
      "D": "迷惑……使之混乱",
      "E": "我不知道这个词",
      "target": "偵察",
      "correct": "A"
  },
  {
      "nom": 61,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspの服</u>をよく買います。",
      "A": "男性喜欢的女式服装",
      "B": "男性使用的衣服",
      "C": "男性制作的衣服",
      "D": "适合男性穿的的女装",
      "E": "我不知道这个词",
      "target": "男物",
      "correct": "B"
  },
  {
      "nom": 62,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>サンダル&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspだ</u>。",
      "A": "脚上穿着凉拖鞋",
      "B": "穿着凉拖鞋摔倒了",
      "C": "脱下了凉拖鞋",
      "D": "踩着凉拖鞋",
      "E": "我不知道这个词",
      "target": "～履き",
      "correct": "A"
  },
  {
      "nom": 63,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：それは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>だ。",
      "A": "认为只有自己被不好地对待",
      "B": "模仿比自己能力强的人",
      "C": "对无可奈何的事情抱有遗憾",
      "D": "无法原谅别人的行为",
      "E": "我不知道这个词",
      "target": "ひがみ",
      "correct": "A"
  },
  {
      "nom": 64,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp叫喚</u>の中にいた。",
      "A": "海水涨到最高的状态",
      "B": "一会儿哭一会儿大声喊的状态",
      "C": "异常欣喜的状态",
      "D": "觉得已经无法获救而放弃的状态",
      "E": "我不知道这个词",
      "target": "阿鼻",
      "correct": "B"
  },
  {
      "nom": 65,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp飼い</u>をしている。",
      "A": "饲养各种各样的动物",
      "B": "大家一起饲养动物",
      "C": "饲养珍稀动物",
      "D": "饲养两只以上同种类的动物",
      "E": "我不知道这个词",
      "target": "多頭",
      "correct": "D"
  },
  {
      "nom": 66,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：みんなで<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を考えた。",
      "A": "书写语言用的符号所表达的意思",
      "B": "不得不做的事情的内容",
      "C": "不完全基于事实的写得有趣的历史故事",
      "D": "最好的手段、方法",
      "E": "我不知道这个词",
      "target": "字義",
      "correct": "A"
  },
  {
      "nom": 67,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が見える。",
      "A": "发信号用的烟",
      "B": "高山连绵的地方",
      "C": "船的前侧",
      "D": "存活了很久的树",
      "E": "我不知道这个词",
      "target": "連嶺",
      "correct": "B"
  },
  {
      "nom": 68,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の神社でお祭りがある。",
      "A": "给远行之人保平安的东西",
      "B": "守护居住在同一个地方的人们的东西",
      "C": "化作人形的东西",
      "D": "居于祈祷地中心处的东西",
      "E": "我不知道这个词",
      "target": "氏神",
      "correct": "B"
  },
  {
      "nom": 69,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を注文した。",
      "A": "气候温暖的国家的水果",
      "B": "英国的威士忌",
      "C": "加淀粉制作的菜肴",
      "D": "清澈的汤",
      "E": "我不知道这个词",
      "target": "コンソメ",
      "correct": "D"
  },
  {
      "nom": 70,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>はいくらですか。",
      "A": "居民交的钱",
      "B": "最高的价格",
      "C": "秋天穿的衣服",
      "D": "卖不出去的东西",
      "E": "我不知道这个词",
      "target": "市町村税",
      "correct": "A"
  },
  {
      "nom": 71,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：油断は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>だ。",
      "A": "最好做一下的事情",
      "B": "不可以做的事情",
      "C": "有时会发生的事情",
      "D": "几乎不发生的事情",
      "E": "我不知道这个词",
      "target": "禁物",
      "correct": "B"
  },
  {
      "nom": 72,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspです</u>。",
      "A": "毛发长",
      "B": "鼻梁高",
      "C": "眼睛大",
      "D": "手指弯曲",
      "E": "我不知道这个词",
      "target": "長髪",
      "correct": "A"
  },
  {
      "nom": 73,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：このやり方には<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>がある。",
      "A": "趣味性、独特性",
      "B": "致命性的缺点",
      "C": "高效率",
      "D": "不稳定、有波动的样子",
      "E": "我不知道这个词",
      "target": "ばらつき",
      "correct": "D"
  },
  {
      "nom": 74,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspマダム</u>と呼ばれている。",
      "A": "有金钱和自由时间的女人",
      "B": "做任何事情都想让大家高兴的女人",
      "C": "比其他人优秀的女人",
      "D": "拥有一颗诚挚之心的女人",
      "E": "我不知道这个词",
      "target": "有閑",
      "correct": "A"
  },
  {
      "nom": 75,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 期</u>の問題を理解する。",
      "A": "从农业转为工业的时期",
      "B": "个人存钱的时期",
      "C": "东西从制作到完成的期间",
      "D": "孩子出生前后的时期",
      "E": "我不知道这个词",
      "target": "周産",
      "correct": "D"
  },
  {
      "nom": 76,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この本を<u>読み&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspました</u>。",
      "A": "发出声音读了",
      "B": "读到了最后",
      "C": "读了一点",
      "D": "能读了",
      "E": "我不知道这个词",
      "target": "～終わる",
      "correct": "B"
  },
  {
      "nom": 77,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を目指す。",
      "A": "拥有丰富兴趣爱好的人",
      "B": "质量好的商品",
      "C": "在东边的国家",
      "D": "像神一样没有缺点",
      "E": "我不知道这个词",
      "target": "完徳",
      "correct": "D"
  },
  {
      "nom": 78,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspに</u>行う。",
      "A": "自主、自发地考虑后",
      "B": "将困难的或者新鲜的事物……",
      "C": "心绪被动摇后",
      "D": "边流利地说边……",
      "E": "我不知道这个词",
      "target": "ボランタリー",
      "correct": "A"
  },
  {
      "nom": 79,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：人の話<u>に&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspを立てる</u>。",
      "A": "集中注意力于……",
      "B": "对……感到吃惊",
      "C": "在心里再默念一遍……",
      "D": "很好地理解了……",
      "E": "我不知道这个词",
      "target": "聞き耳",
      "correct": "A"
  },
  {
      "nom": 80,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：主に<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を勉強している。",
      "A": "江户时期建立的学校",
      "B": "大城市里的银行",
      "C": "与国家有关的规定",
      "D": "有很多农户的山村",
      "E": "我不知道这个词",
      "target": "公法",
      "correct": "C"
  },
  {
      "nom": 81,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：友達の手紙を<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "弄丢了",
      "B": "复印了",
      "C": "藏起来了",
      "D": "私自看了",
      "E": "我不知道这个词",
      "target": "盗み読む",
      "correct": "D"
  },
  {
      "nom": 82,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この作品には<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>がある。",
      "A": "好的感觉、趣味",
      "B": "惊讶、爆发力",
      "C": "痛苦、哀愁",
      "D": "深入的思考、意见",
      "E": "我不知道这个词",
      "target": "趣",
      "correct": "A"
  },
  {
      "nom": 83,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：やり方は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspの</u>状態だ。",
      "A": "按照记得的样子",
      "B": "凭感觉探索",
      "C": "全部都变得可以使用",
      "D": "拜托别人",
      "E": "我不知道这个词",
      "target": "手探り",
      "correct": "B"
  },
  {
      "nom": 84,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：最後に大物を<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>。",
      "A": "借到手了",
      "B": "拧下来了",
      "C": "瞄准击败了",
      "D": "夹在物品之间了",
      "E": "我不知道这个词",
      "target": "仕留める",
      "correct": "C"
  },
  {
      "nom": 85,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：先生が<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>作ったものだった。",
      "A": "亲自动手",
      "B": "压缩后",
      "C": "不经意间",
      "D": "慢悠悠地",
      "E": "我不知道这个词",
      "target": "手ずから",
      "correct": "A"
  },
  {
      "nom": 86,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp歌</u>を聞く。",
      "A": "表达战斗胜利时喜悦的歌",
      "B": "从过去流传下来的歌",
      "C": "融入了公司精神创作出来的歌",
      "D": "表达对逝者哀思的歌",
      "E": "我不知道这个词",
      "target": "哀傷",
      "correct": "D"
  },
  {
      "nom": 87,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：ここには<u>家族&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が多い。",
      "A": "和家人一起来的人们",
      "B": "不喜欢家人的人们",
      "C": "人数少的家庭",
      "D": "喜欢流行事物的家庭",
      "E": "我不知道这个词",
      "target": "～連れ",
      "correct": "A"
  },
  {
      "nom": 88,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の映画を見た。",
      "A": "海中的植物",
      "B": "和自己的国家差异很大的外国",
      "C": "性格和想法奇怪的人",
      "D": "样态不同寻常的动物",
      "E": "我不知道这个词",
      "target": "怪獣",
      "correct": "D"
  },
  {
      "nom": 89,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>でそれを知った。",
      "A": "一般人不知道的故事",
      "B": "刊登着新闻报道的页面",
      "C": "写着规定和命令等的文章",
      "D": "记载了地理特征的书",
      "E": "我不知道这个词",
      "target": "誌面",
      "correct": "B"
  },
  {
      "nom": 90,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：父親と<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspする</u>。",
      "A": "断绝关系",
      "B": "在同一个地方",
      "C": "争论",
      "D": "直接说",
      "E": "我不知道这个词",
      "target": "義絶",
      "correct": "A"
  },
  {
      "nom": 91,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この本は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>をまとめた物です。",
      "A": "教技艺或者学问的老师讲过的话",
      "B": "实际上的复杂情况",
      "C": "战争的详细记录",
      "D": "意外的好消息",
      "E": "我不知道这个词",
      "target": "口伝",
      "correct": "A"
  },
  {
      "nom": 92,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp繚乱の</u>様子だ。",
      "A": "发出声音且在晃动的",
      "B": "清晰可见的",
      "C": "有各种各样好东西的",
      "D": "衣服下面的部分展开着的",
      "E": "我不知道这个词",
      "target": "百花",
      "correct": "C"
  },
  {
      "nom": 93,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>はおもしろい。",
      "A": "纪录现实的电影、电视节目",
      "B": "用电脑制作的设计",
      "C": "搞笑艺人的组合",
      "D": "成为框架的基本思想",
      "E": "我不知道这个词",
      "target": "ドキュメンタリー",
      "correct": "A"
  },
  {
      "nom": 94,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>会議 &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>です。",
      "A": "会议的技术",
      "B": "会议的时间",
      "C": "会议用的显示屏",
      "D": "会议的房间",
      "E": "我不知道这个词",
      "target": "～室",
      "correct": "D"
  },
  {
      "nom": 95,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：電車が<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>来ました。",
      "A": "又",
      "B": "已经",
      "C": "慢慢地",
      "D": "终于",
      "E": "我不知道这个词",
      "target": "やっと",
      "correct": "D"
  },
  {
      "nom": 96,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の話を聞いた。",
      "A": "表示身体肥胖状况数字",
      "B": "用于治疗癌症的药物",
      "C": "用来固定物品的装置",
      "D": "俄罗斯的社会主义思想",
      "E": "我不知道这个词",
      "target": "ＢＭＩ",
      "correct": "A"
  },
  {
      "nom": 97,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が衝突して生じる変化である。",
      "A": "岩石堆叠而成的东西",
      "B": "宇宙空间里的垃圾",
      "C": "浮在海面上的冰块",
      "D": "非常小的物质",
      "E": "我不知道这个词",
      "target": "粒子",
      "correct": "D"
  },
  {
      "nom": 98,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：話し合いは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>だ。",
      "A": "观察对方情况的状态",
      "B": "意见不合的状态",
      "C": "很多事情都定下来了的状态",
      "D": "快要结束的状态",
      "E": "我不知道这个词",
      "target": "大詰め",
      "correct": "D"
  },
  {
      "nom": 99,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：こうすると<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の働きがよくなる。",
      "A": "支配脑部神经的部位",
      "B": "用来做实验或检测的装置",
      "C": "用来消化腹中食物的部位",
      "D": "为了治疗伤病而喝的东西",
      "E": "我不知道这个词",
      "target": "腸",
      "correct": "C"
  },
  {
      "nom": 100,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：それ<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>の業者に頼んでください。",
      "A": "送……上门",
      "B": "在不改变原意的前提下翻译成别的语言",
      "C": "销售商品",
      "D": "组装零部件",
      "E": "我不知道这个词",
      "target": "宅配",
      "correct": "A"
  },
  {
      "nom": 101,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：仕事で<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を使う。",
      "A": "用来打孔的东西",
      "B": "用来测量角度的东西",
      "C": "用来裁纸的东西",
      "D": "用来画线的东西",
      "E": "我不知道这个词",
      "target": "定規",
      "correct": "D"
  },
  {
      "nom": 102,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を探した。",
      "A": "有能力的人",
      "B": "良药",
      "C": "美味的食物",
      "D": "令人欣喜的礼物",
      "E": "我不知道这个词",
      "target": "良材",
      "correct": "A"
  },
  {
      "nom": 103,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>とは何か。",
      "A": "以天为单位工作",
      "B": "加强军备的想法",
      "C": "随心所欲地去行动的想法",
      "D": "厌世的想法",
      "E": "我不知道这个词",
      "target": "ミリタリズム",
      "correct": "B"
  },
  {
      "nom": 104,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>はどこですか。",
      "A": "主战场",
      "B": "日本的县与县之间的分界线",
      "C": "亚洲某个名为“四国”的发展中的地域",
      "D": "日本某个名为“四国”的地方",
      "E": "我不知道这个词",
      "target": "四国",
      "correct": "D"
  },
  {
      "nom": 105,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を覚えるのは大事だ。",
      "A": "给外国作品取的日文名",
      "B": "汉字的右侧的部分",
      "C": "温泉水的科学性质",
      "D": "在戏剧中要说的话",
      "E": "我不知道这个词",
      "target": "つくり",
      "correct": "B"
  },
  {
      "nom": 106,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>について勉強する。",
      "A": "开始写文章时的心情",
      "B": "通过巨大的（压）力使金属变形的方法",
      "C": "像鬼火（火球）一样诡异的东西",
      "D": "开出美丽的花的草",
      "E": "我不知道这个词",
      "target": "圧延",
      "correct": "B"
  },
  {
      "nom": 107,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：意見が<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspされた</u>。",
      "A": "被收回",
      "B": "被说明",
      "C": "被反对",
      "D": "被无视",
      "E": "我不知道这个词",
      "target": "黙殺",
      "correct": "D"
  },
  {
      "nom": 108,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>話す。",
      "A": "一部分",
      "B": "热闹地、喧闹地",
      "C": "慢慢地、认真仔细地",
      "D": "按顺序一点一点地",
      "E": "我不知道这个词",
      "target": "ぺちゃくちゃ",
      "correct": "B"
  },
  {
      "nom": 109,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>と言われている。",
      "A": "只吃美食的人",
      "B": "只在一家公司工作的人",
      "C": "擅长考虑各种事情的人",
      "D": "从别人那里接收信息的人",
      "E": "我不知道这个词",
      "target": "業師",
      "correct": "C"
  },
  {
      "nom": 110,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：その物質の<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を輸入に頼っている。",
      "A": "成为材料的东西",
      "B": "垫着用的厚纸板",
      "C": "全部需求量",
      "D": "汇总起来的一部分",
      "E": "我不知道这个词",
      "target": "全量",
      "correct": "C"
  },
  {
      "nom": 111,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>がたくさんある。",
      "A": "以前投给公司的钱",
      "B": "山里抓动物的地方",
      "C": "青绿色的漂亮石头",
      "D": "上贡给神的物品",
      "E": "我不知道这个词",
      "target": "旧株",
      "correct": "A"
  },
  {
      "nom": 112,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>はおいしい。",
      "A": "一种生长于意大利的绿色蔬菜",
      "B": "一种生活在海洋里的细长形的鱼",
      "C": "一种豆子制成的粉",
      "D": "一种用小麦制成的饮料",
      "E": "我不知道这个词",
      "target": "アナゴ",
      "correct": "B"
  },
  {
      "nom": 113,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：あの人は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>です。",
      "A": "从事研究工作的人",
      "B": "工作需要用到手的人",
      "C": "在农村工作的人",
      "D": "在政府机关工作的人",
      "E": "我不知道这个词",
      "target": "学者",
      "correct": "A"
  },
  {
      "nom": 114,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>でできている。",
      "A": "一种厚纸",
      "B": "一种硬金属",
      "C": "一种植物纤维",
      "D": "一种动物皮",
      "E": "我不知道这个词",
      "target": "麻",
      "correct": "C"
  },
  {
      "nom": 115,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：空気が<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspいる</u>。",
      "A": "美丽清新",
      "B": "完全变温暖了",
      "C": "完全冷下来了",
      "D": "停滞浑浊",
      "E": "我不知道这个词",
      "target": "よどむ",
      "correct": "D"
  },
  {
      "nom": 116,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を書いて送った。",
      "A": "挑重要部分出来讲的东西",
      "B": "关乎社会之基本且已经确定了的东西",
      "C": "通知地非常详细的东西",
      "D": "关于事、物等内心感受到的东西",
      "E": "我不知道这个词",
      "target": "詳報",
      "correct": "C"
  },
  {
      "nom": 117,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼女は<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>この問題に取り組んだ。",
      "A": "以轻松的心态",
      "B": "没办法，不得已",
      "C": "尽管不做也可以，但特意",
      "D": "欣然地，积极推进地",
      "E": "我不知道这个词",
      "target": "あえて",
      "correct": "C"
  },
  {
      "nom": 118,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：彼らは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp活動</u>をした。",
      "A": "将使用过一次的东西再利用的活动",
      "B": "保护环境的活动",
      "C": "援助有困难的人的活动",
      "D": "找工作的活动",
      "E": "我不知道这个词",
      "target": "慈善",
      "correct": "C"
  },
  {
      "nom": 119,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>、そうですか。",
      "A": "吃惊的时候发出的声音",
      "B": "觉得无聊的时候发出的声音",
      "C": "表示理解了的时候发出的声音",
      "D": "预想猜中的时候发出的声音",
      "E": "我不知道这个词",
      "target": "えっ",
      "correct": "A"
  },
  {
      "nom": 120,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：これは<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspしている</u>。",
      "A": "感觉到温暖",
      "B": "干燥",
      "C": "湿润",
      "D": "有东西粘着",
      "E": "我不知道这个词",
      "target": "パサパサ",
      "correct": "B"
  },
  {
      "nom": 121,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>によって歴史が変わった。",
      "A": "来自国王的指示",
      "B": " 贵族引起的事件",
      "C": "农民的抵抗",
      "D": "武士之间的秘密约定",
      "E": "我不知道这个词",
      "target": "勅令",
      "correct": "A"
  },
  {
      "nom": 122,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：この事件には<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp者</u>がいる。",
      "A": "一起干了坏事的人",
      "B": "钱被抢走了的人",
      "C": "带着兴趣来看了的人",
      "D": "采访了的人",
      "E": "我不知道这个词",
      "target": "共犯",
      "correct": "A"
  },
  {
      "nom": 123,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>が壊れた。",
      "A": "导电的机器",
      "B": " 使温度保持恒温的机器",
      "C": "将光线投射得很远的机器",
      "D": "卖票的机器",
      "E": "我不知道这个词",
      "target": "パンタグラフ",
      "correct": "A"
  },
  {
      "nom": 124,
      "text": "<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>：<u>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</u>を取った。",
      "A": "身体表面的硬疙瘩",
      "B": "治疗体内损伤的成分",
      "C": "在上半身积聚的液体",
      "D": "因为受伤而损坏的身体部位",
      "E": "我不知道这个词",
      "target": "胸水",
      "correct": "C"
  }
  ]
}
`